# Introduction to Parallel Programming in Python

## Tutorial goals:

1. Use bash to check system configuration
2. Git, Pycharm integration
3. Python datatypes: list, dict, array, lambda, defaultdict
4. Local and global variables: scope and namespaces
5. click - a convenient module for providing arguments via command line
6. ipyparallel - bulletin-board-style parallelism

### Probably not until next week:
7. mpi4py - collective parallelism
8. mpi4py.futures - bulletin-board style parallelism
9. Intro to nested.parallel

## 1. Use bash to check system configuration

`pwd`  # Print currently accessed directory 

`echo $HOME`  # print the contents of the bash variable `HOME`

`cd $HOME`  # change to the directory `HOME`

`echo $PATH`  # print the contents of the bash variable `PATH`

`which -a python`  # print the directories in the `PATH` that contain a version of python

`echo $PYTHONPATH`  # print the directories where python looks for modules to import

`mkdir src`  # create a new directory to put source code for python modules  
`export PYTHONPATH=$HOME/src:$PYTHONPATH`  # append this src directory to the `PYTHONPATH`

`ls -a`  # list all contents of current directory, including hidden files

`nano .zshrc`  # Use a simple text editor to view the configuration of the bash terminal (In Mac OSX Catalina, the default bash terminal is zsh)  
Add the above `"export"` line to `.zshrc` to permanently configure `PYTHONPATH`

## 2. Git, Pycharm integration

### git commands: pull, stash, add, commit, merge, push

- `git clone https://github.com/neurosutras/nrnpy_tutorial.git .` - download a code repository and put it in a new subdirectory with the repository name
- `git pull origin master` - download any changes to the branch with the name "master" from the remote location named "origin" since you cloned the repository, or since the last time you "pulled"
    - PyCharm will warn you if you have made local changes that would be over-written by the pull operation
- `git stash` - if you want the remote changes to replace your local copy, you can "stash" the changes. On the next pull, your local changes will be over-written
- `git add` - if you want a file that you created to be tracked by git, you can right-click on the filename and "add" it the list of tracked files
- `git commit` - if you have made changes to one or more tracked files locally and you want to update the remote repository, you need to "commit" them to the record. This is just a local operation and does not yet change the upstream remote origin. You can add a message to describe the changes in this commit, and attribute yourself as the author of the changes.
- `git pull` - if in your latest commits, you have made changes to the same lines of the same files as another collaborator, and you try to "pull" remote changes, PyCharm will detect the conflict and give you the opportunity to decide line-by-line which version you would like to use going forward. This is called a "merge" operation.
- `git push` - Once you have merged, commit your changes again. Then you are ready to "push" those commits to the remote origin.

https://www.jetbrains.com/pycharm/download/#section=mac

### In Pycharm:
- Top Menu --> File --> New Project...
- Set "Location" to directory containing nrnpy_tutorial repository
- Set "Python Interpreter" to "Existing Interpreter" and point to python executable in anaconda bin directory
- "Create"
- "Create from existing sources"
- Open project in "New Window"
- Let PyCharm find importable python modules and do some indexing
<br><br>
- Top Menu --> PyCharm --> Preferences...
- Project:nrnpy_tutorial --> Python Interpreter
- Click settings gear on top right --> "Show All"
- Click directory hierarchy icon on bottom "Show paths for the selected interpreter"
- If not already in the list, make sure to "Add" the "parent directory" that contains the subdirectory with your cloned git repository
- Back in the Preferences panel --> Tools --> Terminal
- Make sure the "Shell path" points to your preferred bash executable (e.g. /bin/zsh)
- Apply and close Preferences
<br><br>
- Click the "Terminal" tab on the bottom
- `which python3` to make sure PyCharm Terminal agrees with the system terminal configuration
<br><br>
- Top Menu --> VCS --> Git --> Remotes
- Make sure a remote location with the name "origin" points to the URL of the nrnpy_tutorial on GitHub

## 3. Python datatypes: list, dict, array, lambda, defaultdict

### list

In [1]:
this_list = []  # or list()

In [2]:
this_list.append(1)  # add an item to the end of a list

In [3]:
print(this_list)

[1]


In [4]:
this_list.append(2)

In [5]:
print(this_list)

[1, 2]


In [6]:
# iterate over the values of the items in a list
for item in this_list:
    print(item)

1
2


In [7]:
# iterate over both the indexes and the values of the items in a list
for index, item in enumerate(this_list):
    print(index, item)

0 1
1 2


In [8]:
len(this_list)  # return the number of items in a list

2

In [9]:
this_list.remove(1)  # remove a specific item from a list

In [10]:
this_list.remove(3)  # what if the item is not in the list?

ValueError: list.remove(x): x not in list

In [11]:
print(this_list)

[2]


### dict

In [12]:
this_dict = {}  # or dict()

In [13]:
this_dict['key1'] = 'value1'  # associate a key with a value in a dictionary (keys can be instances of most types)

In [14]:
print(this_dict)

{'key1': 'value1'}


In [15]:
this_dict['key2'] = 'value2'

In [16]:
print(this_dict)

{'key1': 'value1', 'key2': 'value2'}


In [17]:
# by default iterating over a dict just returns the keys
for key in this_dict:
    print(key)

key1
key2


In [18]:
for key in this_dict.keys():
    print(key)

key1
key2


In [19]:
type(this_dict.keys())  # the keys() method returns a "view" of the keys, not a list of the keys

dict_keys

In [20]:
print(this_dict.keys())

dict_keys(['key1', 'key2'])


In [21]:
print(list(this_dict.keys()))  # you can convert a "view" into a list

['key1', 'key2']


In [22]:
# iterate over the values stored in a dictionary - may not be in the order you expect
for value in this_dict.values():
    print(value)

value1
value2


In [23]:
# iterate over both keys and values in a dictionary
for key, value in this_dict.items():
    print(key, value)

key1 value1
key2 value2


In [24]:
# iterate over both keys and values, as well as an index, or running count of the items in a dictionary
for index, (key, value) in enumerate(this_dict.items()):
    print(index, key, value)

0 key1 value1
1 key2 value2


In [25]:
this_dict.pop('key1')  # remove a specific key, value pair from a dictionary

'value1'

In [26]:
print(this_dict)

{'key2': 'value2'}


In [27]:
this_dict.pop('key3')  # what if the key is not in the dictionary?

KeyError: 'key3'

### array

In [28]:
import numpy as np

In [29]:
this_array = np.array([0, 1, 2])

In [30]:
print(this_array)

[0 1 2]


In [31]:
type(this_array)

numpy.ndarray

In [32]:
this_array.shape

(3,)

In [33]:
len(this_array)

3

In [34]:
this_array = np.array(list(range(1, 4)))

In [35]:
print(this_array)

[1 2 3]


In [36]:
this_array = np.arange(1, 8, 2)

In [37]:
print(this_array)

[1 3 5 7]


In [38]:
for index, value in enumerate(this_array):
    print(index, value)

0 1
1 3
2 5
3 7


In [39]:
print(this_array[::-1])  # print the items in an array in reverse order

[7 5 3 1]


In [40]:
print(this_array[:2])  # print the first 2 items in an array

[1 3]


In [41]:
print(this_array[::2])  # print every 2nd item in an array

[1 5]


In [42]:
this_array[3] = 2  # change the value of an item in an array by referring to its index

In [43]:
print(this_array)

[1 3 5 2]


### lambda

In [44]:
# A standard way to define a callable function with input arguments is:
def func_with_overhead(x):
    return x ** 2.

x = np.linspace(0., 10., 11)
y = func_with_overhead(x)

print('x:', x)
print('y:', y)

x: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
y: [  0.   1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]


In [45]:
# An alternative way to create simple callable is:
func_light = lambda x: x ** 2.

y = func_light(x)

print('x:', x)
print('y:', y)

x: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
y: [  0.   1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]


### defaultdict

In [46]:
from collections import defaultdict

### Great for building data structures with nested dictionaries and lists

In [47]:
standard_dict = {}
standard_dict['Aaron']['hair color'] = 'brown'

KeyError: 'Aaron'

In [48]:
if 'Aaron' not in standard_dict:
    standard_dict['Aaron'] = {}
standard_dict['Aaron']['hair color'] = 'brown'

print(standard_dict)

{'Aaron': {'hair color': 'brown'}}


In [49]:
convenient_nested_dict = defaultdict(dict)
convenient_nested_dict['Aaron']['hair color'] = 'brown'

print(convenient_nested_dict)

defaultdict(<class 'dict'>, {'Aaron': {'hair color': 'brown'}})


In [51]:
convenient_dict_of_dict_of_list = defaultdict(lambda: defaultdict(list))  # defaultdicts have to be constructed with a callable

In [52]:
convenient_dict_of_dict_of_list['Aaron']['favorite foods'].extend(['sushi', 'steak', 'mujadara'])

print(convenient_dict_of_dict_of_list)

defaultdict(<function <lambda> at 0x7f89581f5dd0>, {'Aaron': defaultdict(<class 'list'>, {'favorite foods': ['sushi', 'steak', 'mujadara']})})


In [53]:
print(convenient_dict_of_dict_of_list['Aaron']['favorite foods'])

['sushi', 'steak', 'mujadara']


## 4. Local and global variables: scope and namespaces

In [54]:
a = 10

def modify_a():
    a = 20
    print('inside modify_a: value of a: %i' % a)
    
print('outside modify_a: value of a before modify: %i' % a)

modify_a()

print('outside modify_a: value of a after modify: %i' % a)

outside modify_a: value of a before modify: 10
inside modify_a: value of a: 20
outside modify_a: value of a after modify: 10


### globals() and locals() dictionaries

In [55]:
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'this_list = []  # or list()',
  'this_list.append(1)  # add an item to the end of a list',
  'print(this_list)',
  'this_list.append(2)',
  'print(this_list)',
  '# iterate over the values of the items in a list\nfor item in this_list:\n    print(item)',
  '# iterate over both the indexes and the values of the items in a list\nfor index, item in enumerate(this_list):\n    print(index, item)',
  'len(this_list)  # return the number of items in a list',
  'this_list.remove(1)  # remove a specific item from a list',
  'this_list.remove(3)  # what if the item is not in the list?',
  'print(this_list)',
  'this_dict = {}  # or dict()',
  "this_dict['key1'] = 'value1'  # associate a key with a value in a dictionary (

In [56]:
'a' in globals()

True

In [57]:
globals()['a']

10

In [58]:
locals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'this_list = []  # or list()',
  'this_list.append(1)  # add an item to the end of a list',
  'print(this_list)',
  'this_list.append(2)',
  'print(this_list)',
  '# iterate over the values of the items in a list\nfor item in this_list:\n    print(item)',
  '# iterate over both the indexes and the values of the items in a list\nfor index, item in enumerate(this_list):\n    print(index, item)',
  'len(this_list)  # return the number of items in a list',
  'this_list.remove(1)  # remove a specific item from a list',
  'this_list.remove(3)  # what if the item is not in the list?',
  'print(this_list)',
  'this_dict = {}  # or dict()',
  "this_dict['key1'] = 'value1'  # associate a key with a value in a dictionary (

In [59]:
a = 10

def modify_a():
    a = 20
    print('inside modify_a: value of a: %i' % a)
    print('locals():')
    print(locals())
    
print('outside modify_a: value of a before modify: %i' % a)

modify_a()

print('outside modify_a: value of a after modify: %i' % a)

outside modify_a: value of a before modify: 10
inside modify_a: value of a: 20
locals():
{'a': 20}
outside modify_a: value of a after modify: 10


In [60]:
a = 10

def modify_a():
    global a
    a = 20
    print('inside modify_a: value of a: %i' % a)
    print('locals():')
    print(locals())
    
print('outside modify_a: value of a before modify: %i' % a)

modify_a()

print('outside modify_a: value of a after modify: %i' % a)

outside modify_a: value of a before modify: 10
inside modify_a: value of a: 20
locals():
{}
outside modify_a: value of a after modify: 20


In [61]:
a = 10

def modify_a(a):  # this is a required positional argument
    a = 20
    print('inside modify_a: value of a: %i' % a)
    print('locals():')
    print(locals())
    
print('outside modify_a: value of a before modify: %i' % a)

modify_a(a)

print('outside modify_a: value of a after modify: %i' % a)

outside modify_a: value of a before modify: 10
inside modify_a: value of a: 20
locals():
{'a': 20}
outside modify_a: value of a after modify: 10


In [62]:
a = 10

def modify_a(a=15):  # this is an optional keyword argument with a default value
    print('inside modify_a: value of a: %i' % a)
    print('locals():')
    print(locals())
    
print('outside modify_a: value of a before modify: %i' % a)

modify_a()

print('outside modify_a: value of a after modify: %i' % a)

outside modify_a: value of a before modify: 10
inside modify_a: value of a: 15
locals():
{'a': 15}
outside modify_a: value of a after modify: 10


In [63]:
a = 10

def modify_a(a=15):  # this is an optional keyword argument with a default value
    print('inside modify_a: value of a: %i' % a)
    print('locals():')
    print(locals())
    
print('outside modify_a: value of a before modify: %i' % a)

modify_a(a)

print('outside modify_a: value of a after modify: %i' % a)

outside modify_a: value of a before modify: 10
inside modify_a: value of a: 10
locals():
{'a': 10}
outside modify_a: value of a after modify: 10


In [64]:
a = 10

def modify_a(a, verbose=False):  # this has both a required positional argument and an optional keyword argument with a default value
    a = 20
    if verbose:
        print('inside modify_a: value of a: %i' % a)
        print('locals():')
        print(locals())
    
print('outside modify_a: value of a before modify: %i' % a)

modify_a(verbose=True)

print('outside modify_a: value of a after modify: %i' % a)

outside modify_a: value of a before modify: 10


TypeError: modify_a() missing 1 required positional argument: 'a'

In [66]:
a = 10

def modify_a(a, verbose=False):  # this has both a required positional argument and an optional keyword argument with a default value
    a = 20
    if verbose:
        print('inside modify_a: value of a: %i' % a)
        print('locals():')
        print(locals())
    
print('outside modify_a: value of a before modify: %i' % a)

# modify_a(a, verbose=True)
modify_a(a, **{'verbose': True})

print('outside modify_a: value of a after modify: %i' % a)

outside modify_a: value of a before modify: 10
inside modify_a: value of a: 20
locals():
{'a': 20, 'verbose': True}
outside modify_a: value of a after modify: 10


In [67]:
a = 10

def modify_a(*args, **kwargs):  # generic way to catch unknown arguments
    print('args: ', args)
    print('kwargs: ', kwargs)
    if 'a' in kwargs:
        a = kwargs['a']
    else:
        a = 20
    if 'verbose' in kwargs and kwargs['verbose']:
        print('inside modify_a: value of a: %i' % a)
        print('locals():')
        print(locals())
    
print('outside modify_a: value of a before modify: %i' % a)

modify_a(a, verbose=True)

print('outside modify_a: value of a after modify: %i' % a)

outside modify_a: value of a before modify: 10
args:  (10,)
kwargs:  {'verbose': True}
inside modify_a: value of a: 20
locals():
{'args': (10,), 'kwargs': {'verbose': True}, 'a': 20}
outside modify_a: value of a after modify: 10


In [68]:
a = 10

def modify_a(*args, **kwargs):  # generic way to catch unknown arguments
    print('args: ', args)
    print('kwargs: ', kwargs)
    if 'a' in kwargs:
        a = kwargs['a']
    else:
        a = 20
    if 'verbose' in kwargs and kwargs['verbose']:
        print('inside modify_a: value of a: %i' % a)
        print('locals():')
        print(locals())
    
print('outside modify_a: value of a before modify: %i' % a)

modify_a(a=10, verbose=True)

print('outside modify_a: value of a after modify: %i' % a)

outside modify_a: value of a before modify: 10
args:  ()
kwargs:  {'a': 10, 'verbose': True}
inside modify_a: value of a: 10
locals():
{'args': (), 'kwargs': {'a': 10, 'verbose': True}, 'a': 10}
outside modify_a: value of a after modify: 10


## 5. click - a convenient module for providing arguments via command line

## 6. ipyparallel - bulletin-board-style parallelism

### Switch to Pycharm - nrnpy_tutorial repository